### ISSUE TITLE
Wikisource_en_all_novid_2018-03.zim breaks with kiwix-search

### ISSUE THREAD

**Issue by godane** [kiwix/kiwix-lib#122]
This break is linked to searcher.cpp in kiwix-lib. I ran gdb with kiwix-search commands below:

```
guest@debian:/media/guest/Mvgroup/Rachel Project/kiwix$ gdb --args kiwix-search -s -v wikisource_en_all_novid_2018-03.zim heart
GNU gdb (Debian 7.12-6+b1) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from kiwix-search...done.
(gdb) break searcher.cpp:276
No source file named searcher.cpp.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (searcher.cpp:276) pending.
(gdb) run
Starting program: /usr/local/bin/kiwix-search -s -v wikisource_en_all_novid_2018-03.zim heart
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".

Breakpoint 1, kiwix::Searcher::suggestions (this=0x412690, search="heart", 
    verbose=true) at ../src/searcher.cpp:278
278	  this->reset();
(gdb) break +3
Breakpoint 2 at 0xb7f77934: file ../src/searcher.cpp, line 281.
(gdb) run
The program being debugged has been started already.
Start it from the beginning? (y or n) n
Program not restarted.
(gdb) continue
Continuing.

Breakpoint 2, kiwix::Searcher::suggestions (this=0x412690, search="heart", 
    verbose=true) at ../src/searcher.cpp:281
281	    cout << "Performing suggestion query `" << search << "`" << endl;
(gdb) break +6
Breakpoint 3 at 0xb7f779b9: file ../src/searcher.cpp, line 287.
(gdb) continue
Continuing.
Performing suggestion query `heart`

Breakpoint 3, kiwix::Searcher::suggestions (this=0x412690, search="heart", 
    verbose=true) at ../src/searcher.cpp:287
287	  string unaccentedSearch = removeAccents(search);
(gdb) break +7
Breakpoint 4 at 0xb7f779e9: file ../src/searcher.cpp, line 294.
(gdb) continue
Continuing.

Breakpoint 4, kiwix::Searcher::suggestions (this=0x412690, search="heart", 
    verbose=true) at ../src/searcher.cpp:294
294	    std::vector<const zim::File*> zims;
(gdb) break +5
Breakpoint 5 at 0xb7f77a8f: file ../src/searcher.cpp, line 299.
(gdb) continue
Continuing.

Breakpoint 5, kiwix::Searcher::suggestions (this=0x412690, search="heart", 
    verbose=true) at ../src/searcher.cpp:299
299	    zim::Search* search = new zim::Search(zims);
(gdb) break +5
Breakpoint 6 at 0xb7f77b31: file ../src/searcher.cpp, line 304.
(gdb) continue
Continuing.

Breakpoint 6, kiwix::Searcher::suggestions (this=0x412690, search="heart", 
    verbose=true) at ../src/searcher.cpp:304
304	    internal->current_iterator = internal->_search->begin();
(gdb) break +1
Breakpoint 7 at 0xb7f77b77: file ../src/searcher.cpp, line 305.
(gdb) continue
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0xb7ce2782 in ?? () from /lib/i386-linux-gnu/libc.so.6
(gdb) 

```
It breaks on link 305 of searcher.cpp. Before that it kept running. 
NOTE: I question if this is a 32-bit issue cause i think wikisource 2018-01 also crash with kiwix-serve on raspberry pi armhf. I'm only noting it here cause i question if there is some version of some library you guys are using that i'm not which is cause this weird problem on my end.

**Comment by mgautierfr** [comment]
Which version of kiwix-search are you using ? A nightly (and which date) ? A custom version you are compiling (can you publish it) ?

Can you publish the core file of the crash ? (https://collectd.org/wiki/index.php/Core_file see section "Enabling core files")

What the ouput of `backtrace` command in gdb once the segmentation fault appears ?

**Comment by godane** [comment]
here is the backtrace full after the crash:

```
guest@debian:/media/guest/Mvgroup/Rachel Project/kiwix$ gdb --args kiwix-search -s -v wikisource_en_all_novid_2018-03.zim heart
GNU gdb (Debian 7.12-6+b1) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from kiwix-search...done.
(gdb) break searcher.cpp:305
No source file named searcher.cpp.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (searcher.cpp:305) pending.
(gdb) run
Starting program: /usr/local/bin/kiwix-search -s -v wikisource_en_all_novid_2018-03.zim heart
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
Performing suggestion query `heart`

Program received signal SIGSEGV, Segmentation fault.
0xb7ce2782 in ?? () from /lib/i386-linux-gnu/libc.so.6
(gdb) bracktrack
Undefined command: "bracktrack".  Try "help".
(gdb) backtrace full
#0  0xb7ce2782 in ?? () from /lib/i386-linux-gnu/libc.so.6
No symbol table info available.
#1  0xb7758000 in ?? () from /usr/local/lib/i386-linux-gnu/libzim.so.3
No symbol table info available.
#2  0xb76e8d4e in zim::Reader::read<unsigned int> (this=0x43f810, offset=...)
    at ../src/file_reader.h:46
        tmp_buf = "x\343g\267"
#3  0xb76e7efa in zim::Cluster::read_header<unsigned int> (this=0x4bbe40)
    at ../src/cluster.cpp:62
        offset = 4963904
        n_offset = 3077931008
        data_address = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 1}, <No data fields>}
        buffer = <error reading variable: Cannot access memory at address 0x5>
        current = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 13257792429194289728}, <No data fields>}
#4  0xb76e6c92 in zim::Cluster::Cluster (this=0x4bbe40, 
    reader_=<error reading variable: Cannot access memory at address 0x5>, 
    comp=zim::zimcompNone, isExtended=false) at ../src/cluster.cpp:49
        d = {<REAL_TYPEDEF<unsigned long long>> = {v = 3167}, <No data fields>}
        d1 = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 13258156646712062392}, <No data fields>}
#5  0xb76f34fe in zim::FileImpl::getCluster (this=0x40e480, idx=...)
---Type <return> to continue, or q <return> to quit---
    at ../src/fileimpl.cpp:359
        cluster = std::shared_ptr<zim::Cluster> (empty) = {get() = 0x0}
        clusterOffset = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 10746539103}, <No data fields>}
        next_idx = {<REAL_TYPEDEF<unsigned int>> = {
            v = 11861}, <No data fields>}
        nextClusterOffset = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 14164733032}, <No data fields>}
        clusterSize = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 3418193929}, <No data fields>}
        comp = zim::zimcompNone
        extended = false
        reader = std::shared_ptr<const zim::Reader> (use count 3, weak count 0) = {get() = 0x43f810}
#6  0xb76f3770 in zim::FileImpl::getBlobOffset (this=0x40e480, clusterIdx=..., 
    blobIdx=...) at ../src/fileimpl.cpp:377
        cluster = std::shared_ptr<const zim::Cluster> (use count -1010172835, weak count 1407551828) = {get() = 0xbfffecc8}
#7  0xb76e4cbf in zim::Article::getOffset (this=0xbfffee6c)
    at ../src/article.cpp:204
        dirent = std::shared_ptr<const zim::Dirent> (use count 2, weak count 0) = {get() = 0x41292c}
#8  0xb7707966 in zim::Search::begin (this=0x4112a0) at ../src/search.cpp:254
---Type <return> to continue, or q <return> to quit---
        xapianArticle = {file = 
    std::shared_ptr<zim::FileImpl> (use count 2, weak count 0) = {
            get() = 0x40e480}, idx = 2315024}
        zimfile = 0x40e470
        dbOffset = 13252549107483931000
        databasefd = -1208849340
        database = <incomplete type>
        it = 0x40e470
        first = true
        language = ""
        stopwords = ""
        queryParser = 0xb7f7a1e0 <std::_Vector_base<zim::File const*, std::allocator<zim::File const*> >::~_Vector_base()+12>
        prefix = ""
        flags = 4264608
        query = {internal = {px = 0x0}, static MatchNothing = {internal = {
              px = 0x0}, 
            static MatchNothing = <same as static member of an already seen type>, static MatchAll = {internal = {px = 0x409b70}, 
              static MatchNothing = <same as static member of an already seen type>, static MatchAll = <same as static member of an already seen type>}}, 
          static MatchAll = <same as static member of an already seen type>}
        enquire = {internal = {px = 0x14}, static INCLUDE_QUERY_TERMS = 1, 
---Type <return> to continue, or q <return> to quit---
          static USE_EXACT_TERMFREQ = 2}
        keyMaker = 0xb7fa9000
#9  0xb7f77b48 in kiwix::Searcher::suggestions (this=0x412690, search="heart", 
    verbose=true) at ../src/searcher.cpp:304
        zims = std::vector of length 1, capacity 1 = {0x40e470}
        search = 0x4112a0
        unaccentedSearch = "heart"
#10 0x0040156c in main (argc=5, argv=0xbffff3d4)
    at ../src/searcher/kiwix-search.cpp:117
        searchString = "heart"
        p_result = 0xffff
        zimPath = 0xbffff575 "wikisource_en_all_novid_2018-03.zim"
        search = 0xbffff599 "heart"
        verboseFlag = true
        suggestionFlag = true
        option_index = 0
        c = -1
        searcher = 0x412690
        reader = 0x40e3f0
(gdb) 
```

**Comment by godane** [comment]
So i'm starting to think its debian testing cause this problem cause on the armhf it also crash with wikisource. I did a test on raspberry pi 3 using the latest libzim, kiwix-lib, and kiwix-tools code. Here is the gdb backtrack full of the crash on raspberry pi 3:

```
root@debian:/run/initramfs/memory/data# gdb --args kiwix-search -s -v wikisource_en_all_novid_2018-03.zim heart
GNU gdb (Debian 7.12-6+b1) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from kiwix-search...done.
(gdb) break searcher.cpp:35
No source file named searcher.cpp.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (searcher.cpp:35) pending.
(gdb) run
Starting program: /usr/local/bin/kiwix-search -s -v wikisource_en_all_novid_2018-03.zim heart
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Performing suggestion query `heart`

Program received signal SIGSEGV, Segmentation fault.
0x76d5e814 in ?? () from /lib/arm-linux-gnueabihf/libc.so.6
(gdb) backtrace full
#0  0x76d5e814 in ?? () from /lib/arm-linux-gnueabihf/libc.so.6
No symbol table info available.
#1  0x769ef8b0 in zim::BufferReader::read (this=0x54b0acf0, 
    dest=0x7effe7e4 "", offset=..., size=...) at ../src/file_reader.cpp:364
No locals.
#2  0x769de738 in zim::Reader::read<unsigned int> (this=0x54b0acf0, offset=...)
    at ../src/file_reader.h:46
        tmp_buf = "\000\000\000"
#3  0x769ddbf0 in zim::Cluster::read_header<unsigned int> (this=0x54b45e38)
    at ../src/cluster.cpp:62
        offset = 1996378688
        n_offset = 0
        data_address = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 1}, <No data fields>}
        buffer = std::shared_ptr<const zim::Buffer> (use count 510909, weak count 811) = {get() = 0x1}
        current = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 18446744071411049160}, <No data fields>}
#4  0x769dcf24 in zim::Cluster::Cluster (this=0x54b45e38, 
    reader_=std::shared_ptr<const zim::Reader> (expired, weak count 1) = {...}, comp=zim::zimcompNone, isExtended=false) at ../src/cluster.cpp:49
        d = {<REAL_TYPEDEF<unsigned long long>> = {v = 3167}, <No data fields>}
        d1 = {<REAL_TYPEDEF<unsigned long long>> = {
---Type <return> to continue, or q <return> to quit---
            v = 6101181226436001792}, <No data fields>}
#5  0x769e57ba in zim::FileImpl::getCluster (this=0x54ac6948, idx=...)
    at ../src/fileimpl.cpp:359
        cluster = std::shared_ptr<zim::Cluster> (empty) = {get() = 0x0}
        clusterOffset = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 10746539103}, <No data fields>}
        next_idx = {<REAL_TYPEDEF<unsigned int>> = {
            v = 11861}, <No data fields>}
        nextClusterOffset = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 14164733032}, <No data fields>}
        clusterSize = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 3418193929}, <No data fields>}
        comp = zim::zimcompNone
        extended = false
        reader = std::shared_ptr<const zim::Reader> (use count 3, weak count 0) = {get() = 0x54b0acf0}
#6  0x769e591a in zim::FileImpl::getBlobOffset (this=0x54ac6948, 
    clusterIdx=..., blobIdx=...) at ../src/fileimpl.cpp:377
        cluster = std::shared_ptr<const zim::Cluster> (empty) = {
          get() = 0x7effea68}
#7  0x769db774 in zim::Article::getOffset (this=0x7effeb8c)
    at ../src/article.cpp:204
        dirent = std::shared_ptr<const zim::Dirent> (use count 2, weak count 0) ---Type <return> to continue, or q <return> to quit---
= {get() = 0x54acabec}
#8  0x769f44f4 in zim::Search::begin (this=0x54aca300) at ../src/search.cpp:254
        xapianArticle = {file = 
    std::shared_ptr<zim::FileImpl> (use count 2, weak count 0) = {
            get() = 0x54ac6948}, idx = 2315024}
        zimfile = 0x54ac6938
        dbOffset = 6101438308129173088
        databasefd = 1989580916
        database = <incomplete type>
        it = 0x54ac6938
        first = true
        language = ""
        stopwords = ""
        queryParser = 0x0
        prefix = "\000\000\000\000(?m)^[ \\t]*([0-9A-Fa-f]+)[ \\t]+;[ \\t]*([0-9A-Fa-f]+(?:[ \\t]+[0-9A-Fa-f]+)*)[ \\t]*;\\s*(?:(SL)|(SA)|(ML)|(MA))[ \\t]*(?:#.*?)?$|^([ \\t]*(?:#.*?)?)$|^(.*?)$\000\000\000\000\\\000s\000*\000(\000[\000\060\000-\000\071\000A\000-\000F\000]\000+\000)\000\000\000\000\000(?m)^([ "...
        flags = 1996378688
        query = {internal = {px = 0x7effebac}, static MatchNothing = {
            internal = {px = 0x0}, 
            static MatchNothing = <same as static member of an already seen type>, static MatchAll = {internal = {px = 0x54ac2058}, 
---Type <return> to continue, or q <return> to quit---
              static MatchNothing = <same as static member of an already seen type>, static MatchAll = <same as static member of an already seen type>}}, 
          static MatchAll = <same as static member of an already seen type>}
        enquire = {internal = {px = 0x7effebb0}, 
          static INCLUDE_QUERY_TERMS = 1, static USE_EXACT_TERMFREQ = 2}
        keyMaker = 0x0
#9  0x76f8222e in kiwix::Searcher::suggestions (this=0x54aca938, 
    search="heart", verbose=true) at ../src/searcher.cpp:304
        zims = std::vector of length 1, capacity 1 = {0x54ac6938}
        search = 0x54aca300
        unaccentedSearch = "heart"
#10 0x54aab3e4 in main (argc=5, argv=0x7efff154)
    at ../src/searcher/kiwix-search.cpp:117
        searchString = "heart"
        p_result = 0x2
        zimPath = 0x7efff313 "wikisource_en_all_novid_2018-03.zim"
        search = 0x7efff337 "heart"
        verboseFlag = true
        suggestionFlag = true
        option_index = 0
        c = -1
        searcher = 0x54aca938
        reader = 0x54ac68b8
(gdb) 

```
